version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "pizzaapi"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Ubythfkbcbvec2"

  java-app:
    container_name: java-app
    image: pizzaapi_image
    restart: always
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/pizzaapi
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Ubythfkbcbvec2
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update